-- Esquema de la base de datos DeliStars (solo tablas VIVAS).
-- Las tablas del sistema legado (tbl_ventas, tbl_detalle_venta, tbl_trabajador,
-- tbl_roles, tbl_rol_x_usuario) se eliminaron: los pedidos viven en Firestore
-- y el staff se autentica con Firebase (ver migrations/003-drop-dead-tables.sql).
BEGIN;


CREATE TABLE IF NOT EXISTS public.categoria
(
    id_categoria integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre_categoria character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT categoria_pkey PRIMARY KEY (id_categoria)
);

CREATE TABLE IF NOT EXISTS public.tbl_productos
(
    id_producto serial NOT NULL,
    nombre_producto character varying(150) COLLATE pg_catalog."default" NOT NULL,
    descripcion_producto text COLLATE pg_catalog."default",
    precio_venta numeric(12, 2) NOT NULL,
    id_categoria integer,
    image_url1 text COLLATE pg_catalog."default",
    image_url2 text COLLATE pg_catalog."default",
    disponible boolean NOT NULL DEFAULT true,
    CONSTRAINT tbl_productos_pkey PRIMARY KEY (id_producto)
);

CREATE TABLE IF NOT EXISTS public.tbl_sedes
(
    id_sede serial NOT NULL,
    nombre_sede character varying(100) COLLATE pg_catalog."default" NOT NULL,
    telefono_sede character varying(20) COLLATE pg_catalog."default",
    direccion_sede character varying(255) COLLATE pg_catalog."default",
    horario_lunes_jueves text COLLATE pg_catalog."default",
    horario_viernes text COLLATE pg_catalog."default",
    horario_domingo text COLLATE pg_catalog."default",
    horario_sabado text COLLATE pg_catalog."default",
    CONSTRAINT tbl_sedes_pkey PRIMARY KEY (id_sede)
);

CREATE TABLE IF NOT EXISTS public.presentacion_producto
(
    id_presentacion serial NOT NULL,
    id_producto integer NOT NULL,
    tamano character varying(50) COLLATE pg_catalog."default" NOT NULL,
    base character varying(50) COLLATE pg_catalog."default",
    sabor character varying(100) COLLATE pg_catalog."default",
    precio_venta numeric(12, 2) NOT NULL,
    CONSTRAINT presentacion_producto_pkey PRIMARY KEY (id_presentacion)
);

ALTER TABLE IF EXISTS public.tbl_productos
    ADD CONSTRAINT fk_categoria FOREIGN KEY (id_categoria)
    REFERENCES public.categoria (id_categoria) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.presentacion_producto
    ADD CONSTRAINT presentacion_producto_id_producto_fkey FOREIGN KEY (id_producto)
    REFERENCES public.tbl_productos (id_producto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
-- Seeds moved to seeds.sql. Run that file manually when needed.

END;
