-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.categoria
(
    id_categoria integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre_categoria character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT categoria_pkey PRIMARY KEY (id_categoria)
);

CREATE TABLE IF NOT EXISTS public.tbl_detalle_venta
(
    id_detalle_venta serial NOT NULL,
    id_venta integer,
    id_producto integer,
    cantidad_producto integer NOT NULL,
    valor_total_x_producto numeric(12, 2) NOT NULL,
    CONSTRAINT tbl_detalle_venta_pkey PRIMARY KEY (id_detalle_venta)
);

CREATE TABLE IF NOT EXISTS public.tbl_productos
(
    id_producto serial NOT NULL,
    nombre_producto character varying(150) COLLATE pg_catalog."default" NOT NULL,
    descripcion_producto text COLLATE pg_catalog."default",
    precio_venta numeric(12, 2) NOT NULL,
    id_categoria integer,
    image_url1 text COLLATE pg_catalog."default",
    image_url2 text COLLATE pg_catalog."default",
    disponible boolean NOT NULL DEFAULT true,
    CONSTRAINT tbl_productos_pkey PRIMARY KEY (id_producto)
);

CREATE TABLE IF NOT EXISTS public.tbl_rol_x_usuario
(
    id_rol_x_usuario serial NOT NULL,
    id_rol integer,
    id_trabajador integer,
    CONSTRAINT tbl_rol_x_usuario_pkey PRIMARY KEY (id_rol_x_usuario)
);

CREATE TABLE IF NOT EXISTS public.tbl_roles
(
    id_rol serial NOT NULL,
    nombre character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tbl_roles_pkey PRIMARY KEY (id_rol)
);

CREATE TABLE IF NOT EXISTS public.tbl_sedes
(
    id_sede serial NOT NULL,
    nombre_sede character varying(100) COLLATE pg_catalog."default" NOT NULL,
    telefono_sede character varying(20) COLLATE pg_catalog."default",
    direccion_sede character varying(255) COLLATE pg_catalog."default",
    horario_lunes_jueves text COLLATE pg_catalog."default",
    horario_viernes text COLLATE pg_catalog."default",
    horario_domingo text COLLATE pg_catalog."default",
    horario_sabado text COLLATE pg_catalog."default",
    CONSTRAINT tbl_sedes_pkey PRIMARY KEY (id_sede)
);

CREATE TABLE IF NOT EXISTS public.tbl_trabajador
(
    id_trabajador serial NOT NULL,
    nombre_trabajador character varying(100) COLLATE pg_catalog."default" NOT NULL,
    apellido_trabajador character varying(100) COLLATE pg_catalog."default" NOT NULL,
    usuario character varying(70) COLLATE pg_catalog."default",
    usuario_password text COLLATE pg_catalog."default",
    CONSTRAINT tbl_trabajador_pkey PRIMARY KEY (id_trabajador)
);

CREATE TABLE IF NOT EXISTS public.tbl_ventas
(
    id_venta serial NOT NULL,
    fecha_venta timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    id_trabajador integer,
    id_sede integer,
    total_venta numeric(12, 2) DEFAULT 0,
    valor_domicilio numeric(12, 2) DEFAULT 0,
    pedido_confirmado boolean,
    CONSTRAINT tbl_ventas_pkey PRIMARY KEY (id_venta)
);

ALTER TABLE IF EXISTS public.tbl_detalle_venta
    ADD CONSTRAINT tbl_detalle_venta_id_producto_fkey FOREIGN KEY (id_producto)
    REFERENCES public.tbl_productos (id_producto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tbl_detalle_venta
    ADD CONSTRAINT tbl_detalle_venta_id_venta_fkey FOREIGN KEY (id_venta)
    REFERENCES public.tbl_ventas (id_venta) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tbl_productos
    ADD CONSTRAINT fk_categoria FOREIGN KEY (id_categoria)
    REFERENCES public.categoria (id_categoria) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tbl_rol_x_usuario
    ADD CONSTRAINT tbl_rol_x_usuario_id_rol_fkey FOREIGN KEY (id_rol)
    REFERENCES public.tbl_roles (id_rol) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tbl_rol_x_usuario
    ADD CONSTRAINT tbl_rol_x_usuario_id_trabajador_fkey FOREIGN KEY (id_trabajador)
    REFERENCES public.tbl_trabajador (id_trabajador) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tbl_ventas
    ADD CONSTRAINT tbl_ventas_id_sede_fkey FOREIGN KEY (id_sede)
    REFERENCES public.tbl_sedes (id_sede) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.tbl_ventas
    ADD CONSTRAINT tbl_ventas_id_trabajador_fkey FOREIGN KEY (id_trabajador)
    REFERENCES public.tbl_trabajador (id_trabajador) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
-- Seeds moved to seeds.sql. Run that file manually when needed.

END;