-- Seed data for Delistars (move here from init.sql)
-- Run this manually if the Postgres volume already exists:
-- docker cp seeds.sql delistars_postgres:/seeds.sql
-- docker exec -it delistars_postgres psql -U postgres -d delistars1 -f /seeds.sql

BEGIN;

INSERT INTO public.categoria (id_categoria, nombre_categoria) VALUES (1, 'Hamburguesas');
INSERT INTO public.categoria (id_categoria, nombre_categoria) VALUES (2, 'Perros');
INSERT INTO public.categoria (id_categoria, nombre_categoria) VALUES (3, 'Salchipapas');
INSERT INTO public.categoria (id_categoria, nombre_categoria) VALUES (4, 'Combos');
INSERT INTO public.categoria (id_categoria, nombre_categoria) VALUES (5, 'Adiciones');
INSERT INTO public.categoria (id_categoria, nombre_categoria) VALUES (6, 'Deli antojos');
INSERT INTO public.categoria (id_categoria, nombre_categoria) VALUES (7, 'Bebidas');


INSERT INTO public.tbl_sedes (id_sede, nombre_sede, telefono_sede, direccion_sede, horario_lunes_jueves, horario_viernes, horario_domingo, horario_sabado) VALUES (1, 'Santa Lucia, Medellin', '+57 313 506 5720', 'Cra. 87 #48e-3, Santa Rosa De Lima, Medellín, San Javier, Medellín, Antioquia', '4:30pm - 11:30pm', '4:30pm - 12:00pm', '4:00pm - 11:30 pm', '4:00pm - 12:00pm');
INSERT INTO public.tbl_sedes (id_sede, nombre_sede, telefono_sede, direccion_sede, horario_lunes_jueves, horario_viernes, horario_domingo, horario_sabado) VALUES (2, 'Santa Teresita, Medellin', '+57 315 063 4084', 'Cl 35B #87A-165, Laureles - Estadio, Medellín, La América, Medellín, Antioquia', '4:30pm - 11:30pm', '4:30pm - 12:00pm', '4:00pm - 11:30 pm', '4:00pm-12:00pm');

-- Productos (incluye adiciones con id_categoria = 5)
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (1, 'Hamburguesa con queso', 'Deliciosa hamburguesa artesanal con carne seleccionada y una capa generosa de queso fundido para un sabor clásico', 18500, 1, 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946282/delistars/Hamburguesa_sencilla_con_queso_tmffcv.jpg', 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946282/delistars/hamburguesa_sencilla_con_queso2_o62htf.jpg');
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (2, 'Hamburguesa con tocineta', 'La combinación perfecta de carne jugosa y el toque ahumado de nuestra tocineta premium crocante', 18500, 1, 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946282/delistars/Hamburguesa_sencilla_con_tocineta_f08bml.jpg', NULL);
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (3, 'Hamburguesa de pollo', 'Una opción ligera y exquisita preparada con pechuga de pollo de alta calidad, incluye queso o tocineta', 20000, 1, NULL, NULL);
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (4, 'Hamburguesa Especial', 'Nuestra receta estrella elaborada con ingredientes seleccionados para brindar una experiencia de sabor superior', 20000, 1, 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946281/delistars/Hamburguesa_especial_de_carne_pbv6de.jpg', 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946281/delistars/Hamburguesa_especial_de_carne2_u44pk8.jpg');
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (5, 'Hamburguesa Especial de Pollo', 'Todo el sabor de nuestra receta especial ahora con la mejor selección de pollo fresco y jugoso', 21000, 1, 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946282/delistars/hamburguesa_especial_de_pollo2_fxl8a7.jpg', 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946281/delistars/hamburguesa_especial_de_pollo_rkk95y.jpg');
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (6, 'Hamburguesa Mixta', 'El festín definitivo que combina carne de res, pollo y tocineta en una explosion de sabor inigualable', 28500, 1, 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946282/delistars/hamburguesa_mixta_pollo_y_carne_mytu8j.jpg', 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946282/delistars/hamburguesa_mixta_pollo_y_carne2_ekivq5.jpg');
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (7, 'Hamburguesa Sencilla', 'El sabor auténtico y tradicional de Deli Stars en su versión más pura, ideal para cualquier antojo', 17000, 1, 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946283/delistars/hamburguesa_sencilla_solo_carne_lmfchf.jpg', 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946283/delistars/hamburguesa_sencilla_solo_carne2_lsjbgh.jpg');
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (8, 'Hamburguesa Sencilla de Pollo', 'Sabor suave y natural en una hamburguesa de pollo fresca y deliciosamente preparada', 19000, 1, 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946283/delistars/hamburguesa_sencilla_de_pollo_bce2t7.jpg', NULL);
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (9, 'Hamburguesa Super', 'Diseñada para los apetitos más exigentes, esta hamburguesa ofrece una experiencia de sabor maximizada y contundente', 28000, 1, 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946283/delistars/hamburguesa_super_especial_de_carne_lrewdo.jpg', 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946283/delistars/hamburguesa_super_especial_de_carne_2_c6mp62.jpg');
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (10, 'Hamburguesa Super de Pollo', 'La generosidad de nuestra línea Super combinada con la jugosidad y frescura del mejor pollo seleccionado', 29000, 1, 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946283/delistars/hamburguesa_super_de_pollo_w3ltei.jpg', 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946282/delistars/hamburguesa_sencilla_de_pollo_con_tocineta_b0veab.jpg');
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (11, 'Perra Grande', 'Una experiencia única y abundante con los ingredientes más frescos en nuestro formato de hot dog más grande', 20500, 2, 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946283/delistars/Perra_grande_roemp0.jpg', NULL);
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (12, 'Perra Pequeña', 'El antojo ideal con todo el sabor característico de la casa en el tamaño justo para disfrutar en cualquier momento', 18500, 2, 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946283/delistars/perra_peque%C3%B1a_mhbq1h.jpg', NULL);
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (13, 'Perro Grande', 'El hot dog clásico elevado a otro nivel por su tamaño y la calidad superior de sus ingredientes tradicionales', 17000, 2, 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946284/delistars/perro_grande_sin_tocineta_sencillo2_yrngoi.jpg', 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946284/delistars/perro_grande_sin_tocineta_sencillo_w7s6xn.jpg');
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (14, 'Perro Grande con tocineta', 'Experimenta la intensidad de nuestro perro grande potenciada con la textura crocante de la tocineta premium', 19000, 2, 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946283/delistars/perro_grande_con_tocineta_xpwey6.jpg', 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946283/delistars/perro_grande_con_tocineta2_trrniq.jpg');
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (15, 'Perro Pequeño', 'Delicioso, rápido y siempre fresco; el perro caliente ideal para satisfacer tu antojo diario con la mejor receta', 14500, 2, 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946284/delistars/perro_peque%C3%B1o_sin_tocineta_sencillo2_cbvedn.jpg', 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946284/delistars/perro_peque%C3%B1o_sin_tocineta_sencillo_suvtlz.jpg');
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (16, 'Perro Pequeño con tocineta', 'Pequeño en tamaño pero gigante en sabor gracias a su irresistible adición de tocineta perfectamente ahumada', 17000, 2, 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946284/delistars/perro_peque%C3%B1o_con_tocineta_q7jix2.jpg', NULL);
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (17, 'Super Perro Sencillo', 'Una versión robusta y cargada de sabor del perro tradicional para quienes buscan quedar totalmente satisfechos', 19000, 2, 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946285/delistars/super_perro_sin_tocineta_o7e7wt.jpg', NULL);
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (18, 'Super Perro con tocineta', 'El máximo nivel de nuestro Super Perro, enriquecido con láminas de tocineta seleccionada para un gusto superior', 20000, 2, 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946284/delistars/super_perro_con_tocineta_cznenj.jpg', 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946285/delistars/super_perro_con_tocineta2_pcaxsh.jpg');
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (19, 'Super Perro Doble salchicha', 'Para los verdaderos fanáticos de la proteína: doble salchicha y doble sabor en un perro caliente insuperable', 23000, 2, NULL, NULL);
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (20, 'Papastars', 'Nuestra especialidad exclusiva con chicharrones, salchicha, ensalada, viruta de papa y el toque maestro de queso fundido', 27000, 3, 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946283/delistars/PAPASTARS_hdou5s.jpg', NULL);
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (21, 'Salchipapa Especial', 'Una deliciosa montaña de papas crujientes acompañadas de salchicha, tocineta y una porción generosa de queso', 18000, 3, 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946284/delistars/salchipapa_especial_nou0fg.jpg', NULL);
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (22, 'Salchipapa Sencilla', 'La receta clásica y reconfortante de papas y salchicha preparada con el sello de calidad único de Deli Stars', 15000, 3, 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946284/delistars/salchipapa_sencilla_klmsov.jpg', NULL);
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (23, 'Chuzo de Pollo', 'Jugosos trozos de pollo asados a la perfección, el snack proteico ideal para complementar cualquier pedido', 18000, 6, 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946280/delistars/Chuzo_especial_pod5xo.jpg', NULL);
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (24, 'Combo Hamburguesa Especial', 'Disfruta de nuestra Hamburguesa Especial en un paquete completo que incluye papas crujientes y gaseosa fría', 29000, 4, 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946280/delistars/COMBO_HAMBURGUESA_ESPECIAL_mzocss.jpg', NULL);
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (25, 'Combo Hamburguesa Sencilla', 'La combinación perfecta de ahorro y sabor: nuestra hamburguesa clásica con todos sus acompañamientos', 26000, 4, 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946280/delistars/COMBO_HAMBURGUESA_SENCILLA_obzgvw.jpg', NULL);
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (26, 'Combo Hamburguesa Sencilla con queso o tocineta', 'Eleva tu combo sencillo añadiendo la cremosidad del queso o el crujiente de la tocineta premium', 27000, 4, NULL, NULL);
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (27, 'Combo Hamburguesa Super', 'El paquete definitivo para el hambre más voraz, con nuestra hamburguesa más grande y complementos completos', 38500, 4, 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946280/delistars/COMBO_HAMBURGUESA_SUPER_DE_CARNE_shgnsm.jpg', NULL);
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (28, 'Combo Hamburguesa Especial de Pollo', 'Nuestra receta especial de pollo ahora en un menú completo con papas y bebida para tu total deleite', 30000, 4, 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946279/delistars/COMBO_HAMBURGUESA_ESPECIAL_DE_POLLO_om0nwe.jpg', NULL);
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (29, 'Combo Hamburguesa Super de Pollo', 'Experimenta el máximo tamaño en pollo con este combo diseñado para brindar una satisfacción total', 37000, 4, 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946280/delistars/COMBO_HAMBURGUESA_SUPER_DE_POLLO_wlkzuc.jpg', NULL);
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (30, 'Combo Perra Grande', 'El favorito de la casa en su versión más completa, acompañado de papas seleccionadas y gaseosa refrescante', 29500, 4, 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946281/delistars/COMBO_PERRA_GRANDE_fpqoei.jpg', NULL);
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (31, 'Combo Perra Pequeña', 'El equilibrio ideal de sabor y tamaño en un combo pensado para disfrutar de lo mejor de Deli Stars', 27500, 4, 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946281/delistars/COMBO_PERRA_PEQUE%C3%91A_yh5wtd.jpg', NULL);
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (32, 'Combo Perro Grande Sencillo', 'Tradición y abundancia en un solo pedido: nuestro perro grande con papas fritas y bebida fría', 26000, 4, 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946281/delistars/COMBO_PERRO_GRANDE_SENCILLO_bmoofj.jpg', NULL);
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (33, 'Combo Perro Pequeño Sencillo', 'La opción más práctica y deliciosa para una comida rápida con todo el sabor artesanal de nuestra cocina', 23500, 4, 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946280/delistars/COMBO_PERRO_PEQUE%C3%91O_SIN_TOCINETA_SENCILLO_dvdjsb.jpg', NULL);
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (34, 'Combo Perro Pequeño Con Tocineta', 'Pequeño pero potente, este combo con tocineta es el favorito de quienes buscan un sabor intenso', 26000, 4, 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946280/delistars/COMBO_PERRO_PEQUE%C3%91O_CON_TOCINETA_kz12b6.jpg', NULL);
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (35, 'Combo Perro Grande Con Tocineta', 'Una comida redonda que incluye nuestro perro grande, tocineta premium, papas y gaseosa bien fría', 28000, 4, NULL, NULL);
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (36, 'Combo Super Perro Con Tocineta', 'Experimenta la grandeza de nuestro Super Perro con tocineta en un combo que no deja espacio al hambre', 29000, 4, 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946280/delistars/Combo_super_perro_con_tocineta_nsybke.jpg', NULL);
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (37, 'Combo Super Perro Sencillo', 'Potencia y sencillez se unen en este combo abundante diseñado para los verdaderos amantes de los perros calientes', 28000, 4, 'https://res.cloudinary.com/dfx530yml/image/upload/q_auto/f_auto/v1778946281/delistars/COMBO_SUPER_PERRO_SIN_TOCINETA_ml1vmn.jpg', NULL);
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (38, 'Ensalada', 'Frescura garantizada en nuestra ensalada de la casa, el complemento ideal para equilibrar cualquier plato principal', 9000, 5, NULL, NULL);
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (39, 'Carne', 'Adiciona una porción extra de nuestra carne de res seleccionada para potenciar el sabor de tu hamburguesa favorita', 4500, 5, NULL, NULL);
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (40, 'Papas', 'Una porción adicional de nuestras papas fritas, siempre doradas y crujientes, para los que nunca tienen suficientes', 7000, 5, NULL, NULL);
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (41, 'Pollo', 'Agrega más jugosidad a tu pedido con una porción extra de nuestro pollo preparado con la receta especial de la casa', 6500, 5, NULL, NULL);
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (42, 'Queso', 'Doble cremosidad para tu hamburguesa o perro con una porción extra de nuestro queso fundido de alta calidad', 5500, 5, NULL, NULL);
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (43, 'Queso en vaso', 'Disfruta de nuestra salsa de queso fundido por separado, ideal para bañar tus papas o cualquier producto del menú', 7500, 5, NULL, NULL);
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (44, 'Tocineta', 'Aporta ese toque ahumado y crujiente que tanto te gusta con una porción adicional de nuestra tocineta premium', 4000, 5, NULL, NULL);
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (45, 'Salchicha pequeña', 'El complemento perfecto para personalizar tu plato con el sabor tradicional de nuestra salchicha seleccionada', 2500, 5, NULL, NULL);
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (46, 'Salchicha grande', 'Aumenta la satisfacción de tu perro caliente con una salchicha extra de gran tamaño y calidad superior', 3000, 5, NULL, NULL);
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) VALUES (47, 'Salchicha Americana', 'Dale un giro gourmet a tu pedido con el sabor intenso y la textura única de nuestra salchicha americana', 3500, 5, NULL, NULL);

-- 1. Producto contenedor para Jugos de la Casa (id_categoria = 7 - Bebidas)
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) 
VALUES (48, 'Jugos de la Casa', 'Deliciosos jugos naturales preparados al instante. Elige tu sabor, tamaño y base favorita.', 0.00, 7, 'https://res.cloudinary.com/dfx530yml/image/upload/v1782487997/WhatsApp_Image_2026-06-25_at_8.33.14_PM_fux53y.jpg', 'https://res.cloudinary.com/dfx530yml/image/upload/v1782487987/WhatsApp_Image_2026-06-25_at_8.33.53_PM_qlal5g.jpg');

-- 2. Variantes de Jugos de la Casa (id_producto = 48)
INSERT INTO public.presentacion_producto (id_producto, sabor, tamano, base, precio_venta) 
VALUES
(48, 'Limonada de Coco', '14 oz', 'Leche', 7500.00),
(48, 'Limonada de Coco', '1 Litro', 'Leche', 13500.00),
(48, 'Limonada Natural', '14 oz', 'Agua', 6500.00),
(48, 'Limonada Natural', '1 Litro', 'Agua', 11500.00),
(48, 'Guanábana', '14 oz', 'Agua', 6500.00),
(48, 'Guanábana', '14 oz', 'Leche', 7500.00),
(48, 'Guanábana', '1 Litro', 'Agua', 11500.00),
(48, 'Guanábana', '1 Litro', 'Leche', 13500.00),
(48, 'Fresa', '14 oz', 'Agua', 6500.00),
(48, 'Fresa', '14 oz', 'Leche', 7500.00),
(48, 'Fresa', '1 Litro', 'Agua', 11500.00),
(48, 'Fresa', '1 Litro', 'Leche', 13500.00),
(48, 'Mora', '14 oz', 'Agua', 6500.00),
(48, 'Mora', '14 oz', 'Leche', 7500.00),
(48, 'Mora', '1 Litro', 'Agua', 11500.00),
(48, 'Mora', '1 Litro', 'Leche', 13500.00),
(48, 'Piña', '14 oz', 'Agua', 6500.00),
(48, 'Piña', '1 Litro', 'Agua', 11500.00),
(48, 'Maracuyá', '14 oz', 'Agua', 6500.00),
(48, 'Maracuyá', '14 oz', 'Leche', 7500.00),
(48, 'Maracuyá', '1 Litro', 'Agua', 11500.00),
(48, 'Maracuyá', '1 Litro', 'Leche', 13500.00),
(48, 'Tomate de Árbol', '14 oz', 'Agua', 6500.00),
(48, 'Tomate de Árbol', '14 oz', 'Leche', 7500.00),
(48, 'Tomate de Árbol', '1 Litro', 'Agua', 11500.00),
(48, 'Tomate de Árbol', '1 Litro', 'Leche', 13500.00),
(48, 'Guayaba', '14 oz', 'Agua', 6500.00),
(48, 'Guayaba', '14 oz', 'Leche', 7500.00),
(48, 'Guayaba', '1 Litro', 'Agua', 11500.00),
(48, 'Guayaba', '1 Litro', 'Leche', 13500.00),
(48, 'Uva', '14 oz', 'Agua', 6500.00),
(48, 'Uva', '1 Litro', 'Agua', 11500.00);

-- 3. PRODUCTOS SIMPLES (Gaseosas/Bebidas con precio directo, id_categoria = 7)
INSERT INTO public.tbl_productos (id_producto, nombre_producto, descripcion_producto, precio_venta, id_categoria, image_url1, image_url2) 
VALUES
(49, 'Coca Cola Zero 1.5 Litros', 'Bebida embotellada', 7500.00, 7, 'https://res.cloudinary.com/dfx530yml/image/upload/v1782505169/Gemini_Generated_Image_kfhqynkfhqynkfhq_snfl4h.png', ''),
(50, 'Coca Cola Sabor Original 1.5 Litros', 'Bebida embotellada', 8000.00, 7, 'https://res.cloudinary.com/dfx530yml/image/upload/v1782505166/Gemini_Generated_Image_pa60rmpa60rmpa60_xvmuo7.png', ''),
(51, 'Premio 1.5 Litros', 'Bebida embotellada', 8000.00, 7, 'https://res.cloudinary.com/dfx530yml/image/upload/v1782505158/Gemini_Generated_Image_616csw616csw616c_dju9mz.png', ''),
(52, 'Quatro 1.5 Litros', 'Bebida embotellada', 8000.00, 7, 'https://res.cloudinary.com/dfx530yml/image/upload/v1782505172/Gemini_Generated_Image_77yqcb77yqcb77yq_rmog3x.png', ''),
(53, 'Manzana Postobón Pet 400 ml', 'Bebida embotellada', 4000.00, 7, 'https://res.cloudinary.com/dfx530yml/image/upload/v1782505173/Gemini_Generated_Image_8f9vgn8f9vgn8f9v_mqhefh.png', ''),
(54, 'Uva Postobón Pet 400 ml', 'Bebida embotellada', 4000.00, 7, 'https://res.cloudinary.com/dfx530yml/image/upload/v1782505170/Gemini_Generated_Image_6fbalb6fbalb6fba_qrvmlh.png', ''),
(55, 'Naranjada Postobón Pet 400 ml', 'Bebida embotellada', 4000.00, 7, 'https://res.cloudinary.com/dfx530yml/image/upload/v1782505163/Gemini_Generated_Image_30ro0q30ro0q30ro_aibjvq.png', ''),
(56, 'Colombiana Pet 400 ml', 'Bebida embotellada', 4000.00, 7, 'https://res.cloudinary.com/dfx530yml/image/upload/v1782505162/Gemini_Generated_Image_7ebf8s7ebf8s7ebf_ww00k3.png', ''),
(57, 'Coca Cola Sabor Original Pet 400 ml', 'Bebida embotellada', 4500.00, 7, 'https://res.cloudinary.com/dfx530yml/image/upload/v1782506224/Gemini_Generated_Image_9uir949uir949uir_1_ihiwt9.png', ''),
(58, 'Coca Cola Zero Pet 400 ml', 'Bebida embotellada', 4000.00, 7, 'https://res.cloudinary.com/dfx530yml/image/upload/v1782505162/Gemini_Generated_Image_oilg3xoilg3xoilg_dzsn1e.png', ''),
(59, 'Coca Cola Mini 250 ml', 'Bebida embotellada', 3500.00, 7, 'https://res.cloudinary.com/dfx530yml/image/upload/v1782505163/Gemini_Generated_Image_bh26rcbh26rcbh26_jonmhl.png', ''),
(60, 'Agua saborizada manzana', 'Bebida embotellada', 4000.00, 7, 'https://res.cloudinary.com/dfx530yml/image/upload/v1782505588/Gemini_Generated_Image_7rbsuz7rbsuz7rbs_1_q6xtp4.png', ''),
(61, 'Agua saborizada limon', 'Bebida embotellada', 4000.00, 7, 'https://res.cloudinary.com/dfx530yml/image/upload/v1782505636/Gemini_Generated_Image_lnmboslnmboslnmb_1_pisudi.png', ''),
(62, 'Jugo Hit Tropical Personal', 'Bebida embotellada', 3800.00, 7, 'https://res.cloudinary.com/dfx530yml/image/upload/v1782505580/Gemini_Generated_Image_hgopiehgopiehgop_1_ncirgr.png', ''),
(63, 'Jugo Hit Mora Personal', 'Bebida embotellada', 3800.00, 7, 'https://res.cloudinary.com/dfx530yml/image/upload/v1782505729/Gemini_Generated_Image_ng5423ng5423ng54_1_uparkl.png', '');

SELECT setval(pg_get_serial_sequence('public.categoria', 'id_categoria'), (SELECT MAX(id_categoria) FROM public.categoria));
SELECT setval(pg_get_serial_sequence('public.tbl_sedes', 'id_sede'), (SELECT MAX(id_sede) FROM public.tbl_sedes));
SELECT setval(pg_get_serial_sequence('public.tbl_productos', 'id_producto'), (SELECT MAX(id_producto) FROM public.tbl_productos));
SELECT setval(pg_get_serial_sequence('public.presentacion_producto', 'id_presentacion'), (SELECT MAX(id_presentacion) FROM public.presentacion_producto));

END;
